"""piswitch core — pure logic, never imports tkinter.

Split into modules by domain; this re-exports the flat surface that callers and
tests already use, so `core.foo` keeps working regardless of which module foo
now lives in. Note that patching `core.foo` only affects callers that go through
this package — a sibling calling foo directly needs `core.<module>.foo` patched.
"""
from __future__ import annotations

from .paths import (
    agent_dir,
    auth_path,
    data_dir,
    hidden_builtins_path,
    models_path,
    models_store_path,
    presets_path,
    settings_path,
    switch_backups_dir,
)
from .store import (
    OPENAI_PROXY_COMPAT,
    backfill_proxy_compat,
    hide_builtin,
    is_builtin_provider,
    load_auth,
    load_custom,
    load_hidden_builtins,
    load_models_store,
    load_settings,
    merge_openai_proxy_compat,
    read_json,
    unhide_builtin,
    write_json_atomic,
    write_json_bundle,
)
from .backups import (
    BACKUP_RETENTION,
    light_backup,
    list_switch_backups,
    restore_switch_backup,
)
from .auth import (
    api_key_status,
    auth_kind,
    auth_login_state,
    delete_provider_credentials,
    provider_api_key,
    resolve_api_key_value,
    resolve_has_key,
)
from .catalog import (
    DEFAULT_INPUT_TYPES,
    MODEL_METADATA_KEYS,
    build_custom_provider_cfg,
    builtin_model_metadata,
    fetch_models_url,
    format_context_window,
    infer_model_metadata,
    metadata_from_remote,
    model_supports_reasoning,
    parse_model_edits,
    parse_model_ids,
    provider_model_map,
)
from .probe import (
    ANTHROPIC_VERSION,
    CHAT_PROBE_APIS,
    HTTP_USER_AGENT,
    PROBE_PROMPT,
    build_chat_probe,
    fetch_remote_models,
    probe_chat,
    probe_provider,
    supports_chat_probe,
)
from .providers import (
    add_provider_models,
    clear_provider_models,
    delete_custom_provider,
    delete_provider_model,
    delete_provider_models,
    merge_auth_key,
    merge_custom_provider,
    save_custom_provider,
    update_provider_model,
)
from .settings import (
    apply_settings,
    is_default_model,
    is_default_provider,
    set_default_model,
)
from .presets import (
    active_preset_id,
    add_preset,
    delete_preset,
    format_preset_row,
    is_active,
    load_presets,
    new_preset_id,
    preset_from_current,
    save_presets,
    switch_to,
    update_preset,
)
from .transfer import (
    EXPORT_KIND,
    EXPORT_VERSION,
    export_providers,
    import_providers,
)
from .uistate import (
    ACTION_KEYS,
    action_states,
    range_toggle_targets,
)
from .cli import (
    USAGE,
    cli_list,
    cli_model,
    cli_use,
    dispatch,
)
from .paths import _now_ms  # noqa: F401  (tests monkeypatch the clock)

__all__ = [
    "ACTION_KEYS",
    "ANTHROPIC_VERSION",
    "BACKUP_RETENTION",
    "CHAT_PROBE_APIS",
    "DEFAULT_INPUT_TYPES",
    "EXPORT_KIND",
    "EXPORT_VERSION",
    "HTTP_USER_AGENT",
    "MODEL_METADATA_KEYS",
    "OPENAI_PROXY_COMPAT",
    "PROBE_PROMPT",
    "USAGE",
    "action_states",
    "active_preset_id",
    "add_preset",
    "add_provider_models",
    "agent_dir",
    "api_key_status",
    "apply_settings",
    "auth_kind",
    "auth_login_state",
    "auth_path",
    "backfill_proxy_compat",
    "build_chat_probe",
    "build_custom_provider_cfg",
    "builtin_model_metadata",
    "clear_provider_models",
    "cli_list",
    "cli_model",
    "cli_use",
    "data_dir",
    "delete_custom_provider",
    "delete_preset",
    "delete_provider_credentials",
    "delete_provider_model",
    "delete_provider_models",
    "dispatch",
    "export_providers",
    "fetch_models_url",
    "fetch_remote_models",
    "format_context_window",
    "format_preset_row",
    "hidden_builtins_path",
    "hide_builtin",
    "import_providers",
    "infer_model_metadata",
    "is_active",
    "is_builtin_provider",
    "is_default_model",
    "is_default_provider",
    "light_backup",
    "list_switch_backups",
    "load_auth",
    "load_custom",
    "load_hidden_builtins",
    "load_models_store",
    "load_presets",
    "load_settings",
    "merge_auth_key",
    "merge_custom_provider",
    "merge_openai_proxy_compat",
    "metadata_from_remote",
    "model_supports_reasoning",
    "models_path",
    "models_store_path",
    "new_preset_id",
    "parse_model_edits",
    "parse_model_ids",
    "preset_from_current",
    "presets_path",
    "probe_chat",
    "probe_provider",
    "provider_api_key",
    "provider_model_map",
    "range_toggle_targets",
    "read_json",
    "resolve_api_key_value",
    "resolve_has_key",
    "restore_switch_backup",
    "save_custom_provider",
    "save_presets",
    "set_default_model",
    "settings_path",
    "supports_chat_probe",
    "switch_backups_dir",
    "switch_to",
    "unhide_builtin",
    "update_preset",
    "update_provider_model",
    "write_json_atomic",
    "write_json_bundle",
]
